### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [ngx-rocket/core#13]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature.

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by sinedied** [comment]
You should propose the idea on the [Yeoman](https://github.com/yeoman/yeoman) repo, since our core is based on (and tied to) it. But I'm not sure it would be possible, as Template Literal use Mustache-like syntax which may not not play well with every kind of file, opposed to the EJS syntax.

In any case, for compatibility reason I don't think we can implement it on our side, at it is tied to the whole Yeoman ecosystem.

It's frustrating, I know that EJS has not the simplest syntax (and speed) out there, but all Yeoman generators are based on it.
